### ISSUE TITLE
Dopamine Rootless?

### ISSUE THREAD

**Issue by JEmlay** [brendonjkding/accDemo#12]
You mentioned it was updated for rootless about what about Dopamine?  I've experience a few rootless tweaks that still need to be updated for Dopamine.

I tried a few games and none of them worked.  I can press the button, see the speed numbers change but nothing.

Can you please let me know a known game that works so I can test it on my end?  Maybe I'm just getting unlucky with my game choice?

**Comment by brendonjkding** [comment]
Can you confirm they work in rootfull(rootrw) jailbreaks?

**Comment by JEmlay** [comment]
There is no rootful jailbreak for my device.  iPad Pro M1 15.3

**Comment by brendonjkding** [comment]
Then they probably doesn't work anyway, not because in rootless jailbreak.

**Comment by JEmlay** [comment]
Probably, that's why I want to test a known good game.  Do you know a single game that can be speed up?

**Comment by brendonjkding** [comment]
temple run 2

**Comment by JEmlay** [comment]
Yup, that worked.  Thanks!  Just bad luck on the other games.  Zero issue with Dopamine Rootless.
